spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookstoreapi
    username: root
#    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    data: classpath:data/init-data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect


---

server:
  port: 8181

spring:
  session:
    store-type: redis

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    addresses: amqp://localhost:5672/