spring:
#  data:
#    neo4j:
#      uri: bolt://localhost:7687/
#      embedded:
#        enabled: true
#      repositories:
#        enabled: true
#      username: neo4j
#      password: neo4spring_cloud
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

  data:
    mongodb:
      database: bookstore

---
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true
---
server:
  port: 8181

spring:
  session:
    store-type: redis

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    addresses: amqp://localhost:5672/