spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookstoreapi
    username: root
#    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect


---

server:
  port: 8181

spring:
  session:
    store-type: redis